### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by r-labs** [kayooliveira/plinko-game#2]
How does the ball know which hole to go in, and how does it ensure that it actually goes into it? I presume the result is set before the ball falls through one of the pins below correct? Was looking through the code but wasn't able to figure it out. If you could point me to where this is being handled, would be much appreciated.

**Comment by kayooliveira** [comment]
> How does the ball know which hole to go in, and how does it ensure that it actually goes into it? I presume the result is set before the ball falls through one of the pins below correct? Was looking through the code but wasn't able to figure it out. If you could point me to where this is being handled, would be much appreciated.

the ball doesn't "know" where it will land, it's pure physics, in the engine you define some settings like gravity, ball size and other settings.  You can see these settings in '''src/pages/Games/Plinko/components/Game/config/index.ts'''

**Comment by kayooliveira** [comment]
> much

sorry for the delay in answering
