### ISSUE TITLE
how to make the ball always fall into the pre-planned position?

### ISSUE THREAD

**Issue by addsave** [kayooliveira/plinko-game#3]
Example,How can I make the ball always fall seemingly randomly every time into the third space position in the bottom?

**Comment by kayooliveira** [comment]
> Example,How can I make the ball always fall seemingly randomly every time into the third space position in the bottom?

the ball doesn't "know" where it will land, it's pure physics, in the engine you define some settings like gravity, ball size and other settings.  You can see these settings in '''src/pages/Games/Plinko/components/Game/config/index.ts'''


However I found your question quite interesting and will look for a way to make this possible, as soon as I think of something I will reply to this issue or reference it in a commit or pull request.

**Comment by addsave** [comment]
> > 例如，我怎样才能让球每次看起来总是随机落入底部的第三个空间位置？
> 
> 球不“知道”它会落在哪里，它是纯物理的，在引擎中你定义了一些设置，比如重力、球大小和其他设置。您可以在 '''src/pages/Games/Plinko/components/Game/config/index.ts''' 中看到这些设置
> 
> 但是，我发现您的问题非常有趣，并且会寻找一种方法来实现这一点，只要我想到什么，我就会回复此问题或在提交或拉取请求中引用它。

thank you!!

**Comment by addsave** [comment]
> > > 例如，我怎样才能让球每次看起来总是随机落入底部的第三个空间位置？
> > 
> > 
> > 球不“知道”它会落在哪里，它是纯物理的，在引擎中你定义了一些设置，比如重力、球大小和其他设置。您可以在 '''src/pages/Games/Plinko/components/Game/config/index.ts''' 中看到这些设置
> > 但是，我发现您的问题非常有趣，并且会寻找一种方法来实现这一点，只要我想到什么，我就会回复此问题或在提交或拉取请求中引用它。
> 
> thank you!!

You can take a look at this website, it achieves a similar function, every time you bet the server will return the landing point of the ball, thanks again, looking forward to your answer: https://stake.com/casino/games/plinko

**Comment by kayooliveira** [comment]
> > > > 例如，我怎样才能让球每次看起来总是随机落入底部的第三个空间位置？
> 
> > > 
> 
> > > 
> 
> > > 球不“知道”它会落在哪里，它是纯物理的，在引擎中你定义了一些设置，比如重力、球大小和其他设置。您可以在 '''src/pages/Games/Plinko/components/Game/config/index.ts''' 中看到这些设置
> 
> > > 但是，我发现您的问题非常有趣，并且会寻找一种方法来实现这一点，只要我想到什么，我就会回复此问题或在提交或拉取请求中引用它。
> 
> > 
> 
> > thank you!!
> 
> 
> 
> You can take a look at this website, it achieves a similar function, every time you bet the server will return the landing point of the ball, thanks again, looking forward to your answer: https://stake.com/casino/games/plinko

Ok, I'll take a look and soon I should bring updates.

**Comment by addsave** [comment]
> 
hello,how is it?

**Comment by addsave** [comment]
> > > > > 例如，我怎样才能让球每次看起总是随机落入底部的第三个空间位置？
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 球不“知道”它会落在哪儿，它是纯物理的，在引擎中你定义了一些设置，比如重量、球大小和其他设置。你可以在'''src/pages/Games/Plinko/components /Game/config/index.ts''' 中看这些设置
> > 
> > 
> > > > 但是，我发现你的问题取消非常有趣，并且会寻找一种方法来实现这一点，只要我想到什么，我就会恢复这个问题或在提交中签或请求。
> > 
> > 
> > > 
> > 
> > 
> > > 谢谢你！！
> > 
> > 
> > 你可以看看这个网站，它实现了类似的功能，每次下注服务器都会返回球的落点，再次感谢，期待你的回答：https: [//stake.com/casino/games /plinko](https://stake.com/casino/games/plinko)
> 
> 好的，我会看一下，很快我就会带来更新。

hello,how is it?

**Comment by huythansau30** [comment]
Did you found solution?

**Comment by onsare** [comment]
Any solution found to this issue? determine the path of the ball based on the given sequence of movements ("R" for move right and "L" for move left)
