### ISSUE TITLE
Can you give me an example env file to be able to run this locally?

### ISSUE THREAD

**Issue by matlirman** [kayooliveira/plinko-game#5]
A sample env file would go a long way in trying to run this locally and improve upon the designs a bit!

Also, is it possible to increase the size of the whole board at once or will that ruin the physics behind it?

**Comment by matlirman** [comment]
const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY!,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN!,
  projectId: 'plinko-balls',
  storageBucket: 'plinko-balls.appspot.com',
  messagingSenderId: '203383280650',
  appId: import.meta.env.VITE_FIREBASE_APP_ID!,
  measurementId: 'G-4W19TNHHXZ'
}

apiKey
authDomain
appId

are all these directly accessible from firebase?

**Comment by kayooliveira** [comment]
> are all these directly accessible from firebase?

Yes, all on your firebase app config.

**Comment by kayooliveira** [comment]
> Also, is it possible to increase the size of the whole board at once or will that ruin the physics behind it?

To increase the size of the board, you must pay attention to changing the size of the ball, pins and walls, the physics must only be changed if you make changes that are too big.
