### ISSUE TITLE
Failed to load module script. 

### ISSUE THREAD

**Issue by madshaun1984** [kayooliveira/plinko-game#6]
I've setup an env to run this app locally + via Firebase, but when running on either, the following error is thrown when navigating to index.html via a browser.

``` "Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "false". Strict MIME type checking is enforced for module scripts per HTML spec." ```

Any idea how to remedy this?

**Comment by kayooliveira** [comment]
Take a look at the .env.example file that I added to the project, maybe it can help you, check if everything is OK in your firebase app.

**Comment by kayooliveira** [comment]
> I've setup an env to run this app locally + via Firebase, but when running on either, the following error is thrown when navigating to index.html via a browser.
> 
> `"Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "false". Strict MIME type checking is enforced for module scripts per HTML spec."`
> 
> Any idea how to remedy this?

Take a look at the .env.example file that I added to the project, maybe it can help you, check if everything is OK in your firebase app.

**Comment by kayooliveira** [comment]
Due to downtime this issue will be closed.
